version: '3.4'

networks:
  turno-smart-network:

services:
  turno-smart-db:
    container_name: turno-smart-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
     - 8002:1433
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=turn0sm4rt!
    networks:
     - turno-smart-network
    volumes:
      - turno-smart-db-data:/var/opt/mssql

  turno-smart:
    container_name: turno-smart
    image: ${DOCKER_REGISTRY-}turnosmart
    build:
      context: .
      dockerfile: turno-smart/Dockerfile
    ports:
      - 80:8080
      - 443:8081
    depends_on:
      - turno-smart-db
    environment:
      - DB_HOST=turno-smart-db
      - DB_NAME=turno-smart-app
      - DB_SA_PASSWORD=turn0sm4rt!
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
    networks:
     - turno-smart-network

volumes:
  turno-smart-db-data: